# Infrared Config

# Address that Infrared bind and listens to
#
bind: 0.0.0.0:25565

# This is for receiving PROXY Protocol Headers
#
proxyProtocol:
  # Set this to true to enable it.
  # You also need to set trusted CIDRs to use this feature.
  # You can only receive PROXY Protocol Headers from trusted CIDRs.
  #
  receive: false
  
  # List all your trusted CIDRs here.
  # A CIDR is basically a way to talk about a whole range of IPs
  # instead of just one. See here for more info: 
  # https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#IPv4_CIDR_blocks
  #
  trustedCIDRs:
    - 127.0.0.1/32

# Maximum duration between packets before the client gets timed out.
#
keepAliveTimeout: 30s

# Filter are hooks that trigger befor a connection is processed.
# They are used as preconditions to validate a connection.
#
filters:
  # Rate Limiter will only allow an IP address to connect a specified
  # amount of times in a given time frame.
  #
  rateLimiter:
    # Request Limit is the amount of times an IP address can create
    # a new connection before it gets blocked.
    #
    requestLimit: 10
    
    # Windows Length is the time frame for the Request Limit.
    #
    windowLength: 1s

# Reponse that the player sees when there is no server for that domain.
#
notFoundResponse:
  # The status response that should be displayed to the players
  #
  status:

    # The name of the version.
    # This is displayed on the client side when the version is incompatible.
    #
    versionName: "Infrared 1.20.6"

    # The protocol version number determens if the version of the client is compatible with the server.
    # A list of protocol versions can be found here: https://wiki.vg/Protocol_version_numbers
    # Set this to -1 to mirror the client version back.
    #
    protocolNumber: -1
    maxPlayerCount: 0
    playerCount: 0
    playerSamples: []

    # Server icon can be provided as base64 or path to a file.
    #
    icon: ""
    
    # MOTD can be just a string or a JSON Text Component.
    #
    motd: "Server not found"

  # Reason why the player was disconnected during login.
  #
  message: "Server not found"