# This is the domain that players enter in their game client.
# You can have multiple domains here or just one.
# Currently this holds just a wildcard character as a domain
# meaning that is accepts every domain that a player uses.
# Supports '*' and '?' wildcards in the pattern string.
#
domains:
  - "*"

addresses:
  - 127.0.0.1:25565

# Send a PROXY Protocol Header to the server to
# forward the players IP address
#
#sendProxyProtocol: true

# Reponse that the player sees when the connection to the backend server
# times out during status or login request.
#
dialTimeoutResponse:
  status:
    versionName: "Infrared 1.20.6"
    protocolNumber: 766
    maxPlayerCount: 20
    playerCount: 0
    playerSamples: []
    icon: ""
    motd: "Unable to reach backend server"
  message: "Unable to reach backend server"

# Override Status is similar to the dial timeout response status
# but instead you just can override some fields in the status.
#
overrideStatus:
  versionName: "1.20.6"
  protocolNumber: 766
  maxPlayerCount: 20
  playerCount: 0
  playerSamples: []
  icon: ""
  motd: "Unable to reach backend server"