# This is the domain that players enter in their game client.
# You can have multiple domains here or just one.
# Currently this holds just a wildcard character as a domain
# meaning that is accepts every domain that a player uses.
# Supports '*' and '?' wildcards in the pattern string.
#
domains:
  - "*"

addresses:
  - 127.0.0.1:25565

# Send a PROXY Protocol Header to the server to
# forward the players IP address
#
#sendProxyProtocol: true

# Reponse that the player sees when the connection to the backend server
# times out during status or login request.
#
dialTimeoutResponse:
  # The status response that should be displayed to the players
  #
  status:

    # The name of the version.
    # This is displayed on the client side when the version is incompatible.
    #
    versionName: "Infrared 1.20.6"

    # The protocol version number determens if the version of the client is compatible with the server.
    # A list of protocol versions can be found here: https://wiki.vg/Protocol_version_numbers
    # Set this to -1 to mirror the client version back.
    #
    protocolNumber: 766
    maxPlayerCount: 20
    playerCount: 0
    playerSamples:
      - name: ""
        uuid: ""

    # Server icon can be provided as base64 or path to a file.
    #
    icon: ""
    
    # MOTD can be just a string or a JSON Text Component.
    #
    motd: "Unable to reach backend server"

  # Reason why the player was disconnected during login.
  #
  message: "Unable to reach backend server"

# Override Status is similar to the dial timeout response status
# but instead you just can override some fields in the status.
#
overrideStatus:
  versionName: "1.20.6"
  protocolNumber: 766
  maxPlayerCount: 20
  playerCount: 0
  playerSamples:
    - name: ""
      uuid: ""
  icon: ""
  motd: "Unable to reach backend server"